---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-controller
spec:
  replicas: 2
  selector:
    app: my-app-label
  template:
    metadata:
      labels:
        app: my-app-label
    spec:
      containers:
      - name: my-web-container
        image: nginx
        ports:
        - name: http
          containerPort: 80
